import turtle
angle=80
def my_turtle():
    turtle.forward(100)
    turtle.left(87)
    turtle.setheading(127)
    turtle.up()
    turtle.goto(50,40)
    turtle.down()
    turtle.home()
    turtle.circle(25)
def turtle_state():
    turtle_isdown=turtle.isdown()
    turtle_heading=turtle.heading()
    turtle_xcor=turtle.xcor()
    turtle_ycor=turtle.ycor()
    print("turtle is down? ",turtle_isdown)
    print("current angle: ",turtle_heading)
    print("xcor: ",turtle_xcor,"ycor: ",turtle_ycor)
def turtle_square():
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.home()
def turtle_square_parameters(size,angle):
    turtle.pensize(5)
    turtle.color("red")
    turtle.fillcolor("blue")
    turtle.begin_fill()
    turtle.left(angle)
    turtle.forward(size)
    turtle.left(90)
    turtle.forward(size)
    turtle.left(90)
    turtle.forward(size)
    turtle.left(90)
    turtle.forward(size)
    turtle.left(90)
    turtle.home()
    turtle.end_fill()
def main():
    #my_turtle()
    #turtle_state()
    #turtle_square()
    """
    size1=int(input("Enter a size: "))
    turtle_square_parameters(size1,angle)
    size2=int(input("Enter a size: "))
    turtle_square_parameters(size2,angle)
    size3=int(input("Enter a size: "))
    turtle_square_parameters(size3,angle)
    """
    #input("Press any key to continue...")
main()